kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.21.2
  extraPortMappings:
  - containerPort: 32000
    hostPort: 80
  - containerPort: 31443
    hostPort: 443