apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: local-confidential
  labels:
    app: auth
spec:
  realmSelector:
    matchLabels:
      realm: dev
  roles:
  - name: user
    clientRole: true
  client:
    clientId: local-confidential
    clientAuthenticatorType: confidential
    defaultClientScopes:
      - profile
      - email
      - roles
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    protocol: openid-connect
    protocolMappers:
      - name: audience
        protocolMapper: oidc-audience-mapper
        protocol: openid-connect
        config:
          claim.name: audience
          access.token.claim: "true"
          included.client.audience: client-test
      - name: username
        protocolMapper: oidc-usermodel-property-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          claim.name: username
          jsonType.label: String
          user.attribute: username
      - name: roles
        protocolMapper: oidc-usermodel-client-role-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          claim.name: roles
          jsonType.label: String
          multivalued: "true"
      - name: x-hasura-user-id
        protocolMapper: oidc-usermodel-property-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          id.token.claim: "true"
          userinfo.token.claim: "true"
          claim.name: https://hasura\.io/jwt/claims.x-hasura-user-id
          jsonType.label: String
          user.attribute: id
      - name: x-hasura-default-role
        protocolMapper: oidc-hardcoded-claim-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          id.token.claim: "true"
          userinfo.token.claim: "true"
          claim.name: https://hasura\.io/jwt/claims.x-hasura-default-role
          jsonType.label: String
          claim.value: user
      - name: x-hasura-allowed-roles
        protocolMapper: oidc-usermodel-client-role-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          id.token.claim: "true"
          userinfo.token.claim: "true"
          claim.name: x-hasura-allowed-roles
          jsonType.label: String
          multivalued: "true"
          usermodel.clientRoleMapping.clientId: "local-public"
    redirectUris:
      - "*"
    standardFlowEnabled: true